name: Base edge node image build and push
on: 
  push:
    paths:
      - 'base_edge_node/**'  # Specify path to your directory

jobs:
  build-and-push-edge-node-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "aixpand/aixpbuilder"

      - name: Cleanup space
        run: |
          echo "===========docker buildx du ==================="
          docker buildx du
          echo "===========docker buildx prune -f. Add -af if any other space issues. ============"
          docker buildx prune -f
          echo "===========docker buildx du ================="
          docker buildx du
          echo "========================================"


      - name: Build and push GPU
        uses: docker/build-push-action@v5
        with:
          context: ./base_edge_node
          file: ./base_edge_node/Dockerfile
          push: true
          tags: "aidamian/base_edge_node_amd64:latest"

      - name: Build and push CPU
        uses: docker/build-push-action@v5
        with:
          context: ./base_edge_node
          file: ./base_edge_node/Dockerfile_cpu
          push: true
          tags: "aidamian/base_edge_node_amd64_cpu:latest"

      - name: Retag and Push GPU
        run: |
          cd base_edge_node/
          chmod +x retag_and_push.sh  # Ensure the script is executable
          ./retag_and_push.sh "aidamian/base_edge_node_amd64:latest"

      - name: Retag and Push CPU
        run: |
          cd base_edge_node/
          chmod +x retag_and_push.sh  # Ensure the script is executable
          ./retag_and_push.sh  "aidamian/base_edge_node_amd64_cpu:latest"
